default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root

development:
  <<: *default
  database: contentful_dev

test:
  <<: *default
  database: contentful_test

production:
  <<: *default
  database: contentful_prod
